import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Autogenerated from content/. Order comes from `sidebar_position` frontmatter
// and `_category_.json`, both of which are translatable, so a manual sidebar
// here would only add a second thing to keep in sync per locale.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
